# Etapa 1 — Build
FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

# Etapa 2 — Serve con Nginx
FROM nginx:alpine AS runtime
COPY --from=build /app/dist/cowork-frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80